### PR TITLE
A bunch of minor improvements

### PR DESCRIPTION
**Pull request by fbartels**
Hi,

like teased in my last pr here is my first batch of changes. Since I did not want to change options within status.sh I have implemented a separate config file. Additionally I have done smaller bits of cleanup in cleaning up some unnecessary whitespace and removing service names that are already listed in /etc/services.

remove some unnecessary whitespace
externalise configuration options and add an example configuration file
ignore default configuration file in git
remove service entries that are already defined in /etc/services
extend options parser to print help if called with an unknown option (while still allow to be called without an option)
also check the existance of status_hostname_list.txt when run

### CODE REVIEW

**Comment by Cyclenerd** [comment]
I'm curious what's next :-)

**Comment by Cyclenerd** [comment]
I see ``readlink`` seems to be different at *BSD (macOS). Please consider such differences.

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```tr

**Comment by fbartels** [comment]
Lets see what will come up in daily usage ;-)

I've used sntop for quite a long time, but have already retired it a while ago (git blame gives first changes from november 2015) with a bash version that also does port checks with netcat.

One of the things I found useful in sntop is the ability to kick off further actions via an additional alarm script. So the next step would be to find a place to incorporate this here as well.

And sure thing about readlink. Just have Debian based systems here so I did not have that on my mind.

**Comment by Cyclenerd** [comment]
I have just removed `readlink`. I think so many will not work with symlinks ... 

I also stumble across differences between GNU and BSD (https://github.com/Cyclenerd/postinstall). Best to integrate as little as possible. Build everything yourself...

**Pull request merged**
