### PR TITLE
also use command timeout for ping and only ping twice

### PR DESCRIPTION
**Pull request by fbartels**

### CODE REVIEW

**Comment by Cyclenerd** [comment]
`ping` is different between GNU and BSD. `-w` do not exist:

https://www.freebsd.org/cgi/man.cgi?query=ping&sektion=8&manpath=FreeBSD+4.3-RELEASE

**Comment by Cyclenerd** [comment]
So you could check it:
```
	if stat --version &>/dev/null; then
		# GNU
                ping -w
	else
		# BSD
                ping -t
	fi
```
What do you think?

**Comment by Cyclenerd** [comment]
I would also set an extra timeout for ping. I.e. 2 seconds are too little for 5 pings.

**Comment by fbartels** [comment]
Hi, i've made the timeout for ping now separately configurable (as well as the amount of ping attempts). instead of using -w (deadline), i updated it to -2 (timeout), which should be available on OS X as well https://unix.stackexchange.com/a/384252.

**Comment by Cyclenerd** [comment]
but now you're testing something completely different... and with the sec and milliseconds confuses the user. -w and -t would be better to limit maximum runtime.

**Comment by Cyclenerd** [comment]
things get even more complicated. OpenBSD `ping` knows `-w`:

https://man.openbsd.org/ping.8

**Comment by fbartels** [comment]
I've updated the pull request based on your comments

**Comment by Cyclenerd** [comment]
I will merge this now and adjust it right away. The problem with OpneBSD is not considered yet.

**Pull request merged**
