### PR TITLE
Upgrade to Bootstrap 4 & FontAwesome

### PR DESCRIPTION
**Pull request by chrisx8**
I've replaced Bootstrap 3 with Bootstrap 4, which is the more modern alternative to Bootstrap 3. Furthermore, since `glyphicons` are removed from Bootstrap 4, I replaced the `glyphicons` with Font Awesome icons (URL to which is configurable in `config`).

### CODE REVIEW

**Comment by Cyclenerd** [comment]
Very nice :1 To minimize DNS requests, can you please change the URL to: `https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/css/bootstrap.min.css`

**Comment by chrisx8** [comment]
Done. Great idea!

**Comment by Cyclenerd** [comment]
Thank you 👍

**Comment by chrisx8** [comment]
The screenshot might need to be updated, as the look & feel has changed.

I can help with this when I have more time in a couple of days.

**Pull request merged**
