### PR TITLE
fetch unit test script if its not already present

### PR DESCRIPTION
**Pull request by fbartels**

### CODE REVIEW

**Comment by Cyclenerd** [comment]
Hi,

Thanks for the pull request. :+1: 

Please use curl instead of wget: `curl -f "https://raw.githubusercontent.com/lehmannro/assert.sh/v1.1/assert.sh" -o assert.sh` 
That's exactly how the script is loaded at Travis.

Best regards
Nils

**Comment by Cyclenerd** [comment]
Hi,

the old commit cca206c and the new commit b96bcc9 are the same.

Best regards
Nils

**Comment by fbartels** [comment]
Hi Nils,

yes I was aware of that git amend failed on me. Is now fixed.

**Comment by Cyclenerd** [comment]
Thank you very much!

**Comment by fbartels** [comment]
You're welcome.

Will be looking to do some other improvements as well (separate out configuration for example), but at first wanted to get local tests going and that's why I stumbled upon this one.

**Pull request merged**
