### PR TITLE
enable script parameters for script cmd

### PR DESCRIPTION
**Pull request by acullmann**
## Please Complete the Following

- [x] I read [CONTRIBUTING.md](https://github.com/Cyclenerd/static_status/blob/master/CONTRIBUTING.md)
- [x] I used tabs to indent
- [x] I checked my code with [ShellCheck](https://www.shellcheck.net/)

## Removing the Quotes to enable parameters.

I am not quite sure if there is deeper reasoning behind making the $cmd atomic, as there is a whole section in the README.md about it. At least there was nothing mentioned in https://github.com/Cyclenerd/static_status/pull/17 .

Removing the Quotes enables parameters for my usecase and seems not to break anything. (I have a script checking ssl cert end dates and do not wand to create a symlink for each host I am checking).

### example
After my change the following config 
```
script;ls /home|home
script;ls /notexisting|not here
```
leads to this status.json:
```
% cat ~/status.json
[
  {
    "site": "not here",
    "command": "script",
    "status": "Fail",
    "updated": "2021-12-08 16:44:28 UTC"
  },
  {
    "site": "home",
    "command": "script",
    "status": "OK",
    "updated": "2021-12-08 16:44:28 UTC"
  }
]
```

### CODE REVIEW

**Comment by Cyclenerd** [comment]
Hi, thank you. If you are sure that it does not break anything, feel free to adjust the README. It is currently described that no parameters are supported. Your change makes the note unnecessary.

**Comment by Cyclenerd** [comment]
There was a major change. Feel free to check again and resolve the conflict.

**Comment by acullmann** [comment]
Sorry for the long delay - holiday business... Happy New Year to you all!

I resolved the conflict and updated the readme.

I also tweaked my proposal to actually run in a subshell. This way even `exit` can be executed:

```
script;exit 80|a degration test
```

**Comment by Cyclenerd** [comment]
Thank you 👍

**Pull request merged**
