### PR TITLE
Additional grep check

### PR DESCRIPTION
**Pull request by acullmann**
Hi Cyclenerd,

Thanks for that great tool! I added a grep check that checks for keywords on a webpage.

It's an extension to the curl check: curl downloads the webpage and pipes it to grep, that checks if the keyword is in the page.

This is useful to not only check the web server but the whole application behind it in cases where the web server might return 200 but not the expected content. In my use case: I check if my sync'n'share application delivers a expected file and thus have a basic check for the whole storage backend.

Cheers
Alex

### CODE REVIEW

**Comment by Cyclenerd** [comment]
Thanks for the pull request. I will check the change after my vacation 🏖️.

**Comment by Cyclenerd** [comment]
I've looked at the pull now. Please remove the e-mail function. Has not to do with the description of the pull. There is certainly also a better solution. Better would be a second script which checks the output of `status.sh loud`. An e-mail could be sent if the last text output was changed.

**Comment by acullmann** [comment]
Now it was me who was on vacation :-)

I see your point regarding the emails - i did not mean to push it in this pull request in the beginning...  Now the pull request is back to grep.

**Comment by Cyclenerd** [comment]
Thank you 👍

**Pull request merged**
